### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mahzi4ar** [libre-tube/libre-tube.github.io#6]
Add license  for website code

**Comment by Bnyro** [comment]
> Add license for website code
Do you mean on the Github Page or on the Website itself?

**Comment by Bnyro** [comment]
Thx for the hint, added it.

**Comment by Bnyro** [comment]
Gonna close it, just reopen it if I forgot to add it somewhere else too

**Comment by krypciak-zz** [comment]
GNU GPLv3 license missing in website's code (https://libre-tube.github.io/app.js, https://github.com/libre-tube/libre-tube.github.io/blob/main/app.js).
LibreJS doesn't like it :(

**Comment by Bnyro** [comment]
@krypciak Where should I add it there?

**Comment by Bnyro** [comment]
> GNU GPLv3 license missing in website's code (https://libre-tube.github.io/app.js, https://github.com/libre-tube/libre-tube.github.io/blob/main/app.js). LibreJS doesn't like it :(

@krypciak I'll try to add support for it, but I can't get it accept my javascript at the moment. At least images are now visible in LibreJS

**Comment by Bnyro** [comment]
@krypciak I made it work, it should be 100 per cent compatible with LibreJS now. Thank you for telling me :)

**Comment by krypciak-zz** [comment]
Works fine now, even LocalCDN doesn't yell about anything

**Comment by Bnyro** [comment]
> Works fine now, even LocalCDN doesn't yell about anything

Happy to hear :)
