### ISSUE TITLE
Clicking on donations redirects to (Image below)

### ISSUE THREAD

**Issue by kamlendras** [libre-tube/libre-tube.github.io#67]
(https://github.com/libre-tube/libre-tube.github.io/assets/96082996/9d2831a0-8ebd-4046-8768-7df0a134d1b0)

**Comment by Bnyro** [comment]
Thanks for the report, fixed in https://github.com/libre-tube/libre-tube.github.io/commit/5861d657ad34c91856fb4e9deb8dc6d83f8c60ac
