### ISSUE TITLE
Where are downloaded files stored? is unclear

### ISSUE THREAD

**Issue by nienienienie** [libre-tube/libre-tube.github.io#71]
content added in https://github.com/libre-tube/libre-tube.github.io/pull/70 is unclear

> Downloaded files are stored in external private storage
              (<code>Android/data/com.github.libretube</code>).<br/>
              Note that since Android 11, the <code>READ_EXTERNAL_STORAGE</code>
              permission does not grant third party apps access to external
	      private storage, requiring workarounds.<br/>
              The (usually hidden, not to be confused with Files by Google)
              Android built-in Files app will always have access to this
	      directory. <br/>
	      In the downloaded files, audio and video are separated. Hence it
	      is recommended to exclusively use LibreTube for playing downloaded
	      media.

It would be nice to at least give a hint what to look for when trying to do the "requiring workarounds".

**Comment by Bnyro** [comment]
It's not recommended to do so, so it's out of scope to add more information about accessing these files.
